name: testando-modulo-terraform
run-name: ${{ github.actor }} is learning Github Actions
on:
  push:
jobs:
  tfsec:
    run-on: ubuntu-version
    steps:
      - name: Baixando Codigo
      - uses: actions/checkout@v4
      - name: Instalando o tfsec
      - run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash  # Executar comando lรก dentro da instancia do Github
      - name: executando o tfsec
      - run: ls -la